version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade --force-reinstall awscli
      - pip install -r requirements.txt
      - printenv
  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - export BRANCH_NAME_NORM=$(echo 'sagemakerwucicd')
      - export MODEL_PACKAGE_GROUP_NAME=$(echo 'sagemakerwuchurncicdgroup')
      - export MODEL_NAME=$(echo 'sagemakerwuchurncicdmodel')
      - export SAGEMAKER_PIPELINE_ROLE_ARN=$(echo 'arn:aws:iam::018079024734:role/BC_SageMaker')
      - export COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:-${COMMIT_HASH:-}}
      - export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - python run_pipeline.py --region $AWS_DEFAULT_REGION --experiment-name $BRANCH_NAME_NORM --model-package-group-name $MODEL_PACKAGE_GROUP_NAME --model-name $MODEL_NAME  --commit-id $COMMIT_HASH --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN
